package com.useruser.followay.domain.models

const val SEND_LOCATION_WORKER = "send location worker"


//commands
const val GOOGLE_LOGIN_COMMAND = 1001
const val FACEBOOK_LOGIN_COMMAND = 1002
const val LOGIN_CLICK_COMMAND = 1003
const val OPEN_LOGIN_FRAGMENT_COMMAND = 1004
const val OPEN_SELECT_USER_TYPE_FRAGMENT_COMMAND = 1005
const val OPEN_SEND_INVITATION_FRAGMENT_COMMAND = 1006
const val OPEN_SELECT_NAME_GENDER_FRAGMENT_COMMAND = 1007
const val SEND_INVITATION_CLICK_COMMAND = 1008
const val DONE_CLICK_COMMAND = 1009
const val OPEN_PHONE_CONNECTED_FRAGMENT_COMMAND = 1010
const val OPEN_LOCATION_MAP_FRAGMENT_COMMAND = 1011
const val GO_TO_MAP_COMMAND = 1012
const val OPEN_GALLERY_COMMAND = 1013

//request code
const val REQUEST_CODE_ACCESS_FINE_LOCATION = 2001
const val REQUEST_CODE_ACCESS_BACKGROUND_LOCATION = 2002
const val REQUEST_CODE_GOOGLE_SIGN_IN = 2003
const val REQUEST_CODE_READ_EXTERNAL_STORAGE = 2004
const val REQUEST_CODE_OPEN_GALLERY = 2005

const val USER_TYPE_PARENT = 3001
const val USER_TYPE_KID = 3002

const val GOOGLE_REGISTRATION = 4001
const val FACEBOOK_REGISTRATION = 4002

const val USER_GENDER_MALE = 5001
const val USER_GANDER_FEMAIL = 5002